spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  datasource: #DB 접속정보
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://gambtidb.c4kbbredlqua.ap-northeast-2.rds.amazonaws.com/gambti?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ssafy
    password: gambti123!

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      read-only: false
      connection-test-query: SELECT 1

  jpa: #JPA 설정
    properties:
      hibernate:
        #https://dololak.tistory.com/465, https://gigas-blog.tistory.com/119
        dialect: org.hibernate.dialect.MariaDBDialect
        #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
        show_sql: false #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
        format_sql: false
        #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
        use_sql_comments: false

security:
  firebase-props:
    database-url: ${FIREBASE_DATABASE}
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5

  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: ${DOMAIN}
    path: /

  allow-credentials: true

  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:3000
    - https://dev.gambti.com
    - http://dev.gambti.com
    - https://gambti.com
    - http://gambti.com

  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS

  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token

  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /swagger-ui.html
    - /swagger-ui/**
    - /swagger/**
    - /swagger-resources/**
    - /api-docs/**
    - /webjars/**
    - /admin/**
    - /games/find/**
    - /games/recommends/**
    - /search/**
    - /games/detail/**

  exposed-headers:
    - X-Xsrf-Token

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /**
---

#로컬용
spring:
  config:
    activate:
      on-profile: local

  jpa: #JPA 설정
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    context-path: /v1

---
#dev서버용
spring:
  config:
    activate:
      on-profile: dev

  jpa: #JPA 설정
    hibernate:
      ddl-auto: none

server:
  port: 8081
  servlet:
    context-path: /v1


---
#production 서버용
spring:
  config:
    activate:
      on-profile: prod

  jpa: #JPA 설정
    hibernate:
      ddl-auto: none

server:
  port: 8081
  servlet:
    context-path: /v1