spring:
  profiles:
    active: local

  datasource: #DB 접속정보
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://gambtidb.c4kbbredlqua.ap-northeast-2.rds.amazonaws.com:3306/gambti/serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: gambti123!

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      read-only: false
      connection-test-query: SELECT 1

  jpa: #JPA 설정
    properties:
      hibernate:
      #https://dololak.tistory.com/465, https://gigas-blog.tistory.com/119
      dialect: org.hibernate.dialect.MariaDBDialect
      #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
      show_sql: true #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
      format_sql: true
      #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
      use_sql_comments: true

---
#로컬용
spring:
  config:
    activate:
      on-profile: local

#devtool - restart 사용 false는 너무 잦은 restart를 막음
  restart:
    enabled: true

#로컬용 redis 만들어지면 넣기
#  redis:
#    host:
#    port: 6380

server:
  port: 8081
  servlet:
    context-path: /rest-api

---
#dev서버용
spring:
  config:
    activate:
      on-profile: dev

#redis서버 만들어지면 넣기
#  redis:
#    host:
#    port: 6379

server:
  port: 8082
  servlet:
    context-path: /rest-api


---
#production 서버용
spring:
  config:
    activate:
      on-profile: prod

  redis:
    host: redis
    port: 6379

server:
  port: 8080